# -*- coding: utf-8 -*-
from biztest.util.easymock.easymock import Easymock


class RepayBeiyinMock(Easymock):
    def update_repay_result(self, repay_amount, due_bill_no, withhold_channel="BEIYIN", pay_status="SUCCESS"):
        # BAOFU_KUAINIU 代偿后还款
        # BEIYIN 代偿前还款
        # KUAINIU_PAY  切我方代扣
        api = "/mozhibeiyin/repay.result"
        mode = {
            "code": 0,
            "message": "成功",
            "data": {
                "repayAmount": 60225,
                "failCode": 4523,
                "repayResultList": [{
                    "amount": repay_amount,
                    "repayItems": [{
                        "termPrincipal": 0,
                        "termInterPenalty": 0,
                        "termAmount": 60225,
                        "termPrinPenalty": 0,
                        "termInterest": 0,
                        "termFee": 0,
                        "termInsuranceAmount": 0
                    }, ],
                    "outOrderNo": due_bill_no,
                    "status": pay_status,
                    "authorizeChannel": withhold_channel
                }],
                "repayResult": "代扣成功",
                "outOrderNo": "TMZ-" + due_bill_no,
                "repayStatus": pay_status
            }
        }
        self.update(api, mode)

    def update_repay_list(self, due_bill_no, pre_principal, pre_interest, late_interest=0, term=1, status='REPAY'):
        api = "/mozhibeiyin/repay.list"
        pre_repay_amount = int(pre_principal) + int(pre_interest)
        mode = {
            "code": 0,
            "message": "成功",
            "data": [{
                "preRepayPrincipal": pre_principal,
                "repayAmount": 60169,
                "bankName": "中国建设银行",
                "preRepayAmount": pre_repay_amount,
                "cardNo": "5522458145187710",
                "preRepayFee": 0,
                "loanTime": 1619428012303,
                "preRepayOvdInterPenalty": 0,
                "currentTerm": 1,
                "preRepayInterest": pre_interest,
                "overdueDays": 0,
                "repayPlanItems": [{
                    "termPrincipal": 55813,
                    "termInterPenalty": 0,
                    "shouldRepayDate": "20210526",
                    "termAmount": 60169,
                    "overdueDays": 0,
                    "termPrinPenalty": late_interest,
                    "termNo": term,
                    "termGuaranteeAmount": 0,
                    "termInterest": 4356,
                    "termFee": 0,
                    "termInsuranceAmount": 0
                }],
                "repayInterest": 4356,
                "preGuaranteeAmount": 0,
                "termNum": 6,
                "prePenalty": 0,
                "insuranceAmount": 0,
                "repayPrincipal": 55813,
                "preInsuranceAmount": 0,
                "guaranteeAmount": 0,
                "abbreviation": "CCB",
                "outOrderNo": due_bill_no,
                "loanAmount": 600000,
                "preRepayOvdPrinPenalty": 0,
                "repayFee": 0,
                "repayDate": "20210526",
                "interPenalty": 0,
                "prinPenalty": 57,
                "status": status
            }
            ]
        }
        self.update(api, mode)

    def update_repay_trail(self, principal, interest):
        api = "/mozhibeiyin/repay.ext.trial"
        total_amount = int(principal) + int(interest)
        mode = {
            "code": 0,
            "message": "自动化测试试算成功",
            "data": {
                "repayPrincipal": principal,
                "repayAmount": total_amount,
                "repayInterest": interest,
                "repayPenalty": 0
            }
        }
        self.update(api, mode)

    # 刷罚息会调这个接口
    def update_repay_capital_plan(self, due_bill_no, late_interest=150):
        api = "/mozhibeiyin/loan.record.detail"
        mode = {
            "code": 0,
            "message": "成功",
            "data": {
                "effectiveDate": "20210927",
                "applyDate": "20210927",
                "loanAmount": 500000,
                "status": "OVERDUE",
                "termNum": 12,
                "repayMethod": "FIXED_INSTALLMENT",
                "outOrderNo": due_bill_no,
                "contractList": [],
                "clearTime": 0,
                "paidAmount": 0,
                "paidPrinAmount": 0,
                "paidInterAmount": 0,
                "paidFeeAmount": 0,
                "paidPenalty": 0,
                "paidInsuranceAmount": None,
                "bindCardNo": "6212261702031544026",
                "bindCardNoEncrypt": "enc_03_3038220127566301184_094",
                "bindBankCode": "ICBC",
                "bindBankName": "工商银行",
                "couponNo": None,
                "couponType": None,
                "dayRate": "0.0667",
                "reductionAmount": 0,
                "prePenalty": 0,
                "repayPlanItems": [{
                    "termNo": 1,
                    "shouldRepayDate": "20211027",
                    "termStatus": "REPAING",
                    "repayCategory": 1,
                    "termAmount": 47330,
                    "termPrincipal": 37280,
                    "termInterest": 10000,
                    "termPrinPenalty": late_interest,
                    "termInterPenalty": 0,
                    "termInsuranceAmount": 0,
                    "paidTermInsuranceAmount": 0,
                    "termFee": 0,
                    "paidTime": 0,
                    "paidTermAmount": 0,
                    "paidTermPrincipal": 0,
                    "paidTermInterest": 0,
                    "paidTermPrinPenalty": 0,
                    "paidTermInterPenalty": 0,
                    "paidTermFee": 0,
                    "overdueDays": 2,
                    "overdueAmt": 47330,
                    "preRepay": "N",
                    "overdue": "Y"
                },
                    {
                        "termNo": 2,
                        "shouldRepayDate": "20211127",
                        "termStatus": "PAYING",
                        "repayCategory": 1,
                        "termAmount": 47280,
                        "termPrincipal": 37717,
                        "termInterest": 9563,
                        "termPrinPenalty": 0,
                        "termInterPenalty": 0,
                        "termInsuranceAmount": 0,
                        "paidTermInsuranceAmount": 0,
                        "termFee": 0,
                        "paidTime": 0,
                        "paidTermAmount": 0,
                        "paidTermPrincipal": 0,
                        "paidTermInterest": 0,
                        "paidTermPrinPenalty": 0,
                        "paidTermInterPenalty": 0,
                        "paidTermFee": 0,
                        "overdueDays": 0,
                        "overdueAmt": 0,
                        "preRepay": "N",
                        "overdue": "N"
                    },
                    {
                        "termNo": 3,
                        "shouldRepayDate": "20211227",
                        "termStatus": "PAYING",
                        "repayCategory": 1,
                        "termAmount": 47280,
                        "termPrincipal": 38780,
                        "termInterest": 8500,
                        "termPrinPenalty": 0,
                        "termInterPenalty": 0,
                        "termInsuranceAmount": 0,
                        "paidTermInsuranceAmount": 0,
                        "termFee": 0,
                        "paidTime": 0,
                        "paidTermAmount": 0,
                        "paidTermPrincipal": 0,
                        "paidTermInterest": 0,
                        "paidTermPrinPenalty": 0,
                        "paidTermInterPenalty": 0,
                        "paidTermFee": 0,
                        "overdueDays": 0,
                        "overdueAmt": 0,
                        "preRepay": "N",
                        "overdue": "N"
                    },
                    {
                        "termNo": 4,
                        "shouldRepayDate": "20220127",
                        "termStatus": "PAYING",
                        "repayCategory": 1,
                        "termAmount": 47280,
                        "termPrincipal": 39298,
                        "termInterest": 7982,
                        "termPrinPenalty": 0,
                        "termInterPenalty": 0,
                        "termInsuranceAmount": 0,
                        "paidTermInsuranceAmount": 0,
                        "termFee": 0,
                        "paidTime": 0,
                        "paidTermAmount": 0,
                        "paidTermPrincipal": 0,
                        "paidTermInterest": 0,
                        "paidTermPrinPenalty": 0,
                        "paidTermInterPenalty": 0,
                        "paidTermFee": 0,
                        "overdueDays": 0,
                        "overdueAmt": 0,
                        "preRepay": "N",
                        "overdue": "N"
                    },
                    {
                        "termNo": 5,
                        "shouldRepayDate": "20220227",
                        "termStatus": "PAYING",
                        "repayCategory": 1,
                        "termAmount": 47280,
                        "termPrincipal": 40110,
                        "termInterest": 7170,
                        "termPrinPenalty": 0,
                        "termInterPenalty": 0,
                        "termInsuranceAmount": 0,
                        "paidTermInsuranceAmount": 0,
                        "termFee": 0,
                        "paidTime": 0,
                        "paidTermAmount": 0,
                        "paidTermPrincipal": 0,
                        "paidTermInterest": 0,
                        "paidTermPrinPenalty": 0,
                        "paidTermInterPenalty": 0,
                        "paidTermFee": 0,
                        "overdueDays": 0,
                        "overdueAmt": 0,
                        "preRepay": "N",
                        "overdue": "N"
                    },
                    {
                        "termNo": 6,
                        "shouldRepayDate": "20220327",
                        "termStatus": "PAYING",
                        "repayCategory": 1,
                        "termAmount": 47280,
                        "termPrincipal": 41553,
                        "termInterest": 5727,
                        "termPrinPenalty": 0,
                        "termInterPenalty": 0,
                        "termInsuranceAmount": 0,
                        "paidTermInsuranceAmount": 0,
                        "termFee": 0,
                        "paidTime": 0,
                        "paidTermAmount": 0,
                        "paidTermPrincipal": 0,
                        "paidTermInterest": 0,
                        "paidTermPrinPenalty": 0,
                        "paidTermInterPenalty": 0,
                        "paidTermFee": 0,
                        "overdueDays": 0,
                        "overdueAmt": 0,
                        "preRepay": "N",
                        "overdue": "N"
                    },
                    {
                        "termNo": 7,
                        "shouldRepayDate": "20220427",
                        "termStatus": "PAYING",
                        "repayCategory": 1,
                        "termAmount": 47280,
                        "termPrincipal": 41798,
                        "termInterest": 5482,
                        "termPrinPenalty": 0,
                        "termInterPenalty": 0,
                        "termInsuranceAmount": 0,
                        "paidTermInsuranceAmount": 0,
                        "termFee": 0,
                        "paidTime": 0,
                        "paidTermAmount": 0,
                        "paidTermPrincipal": 0,
                        "paidTermInterest": 0,
                        "paidTermPrinPenalty": 0,
                        "paidTermInterPenalty": 0,
                        "paidTermFee": 0,
                        "overdueDays": 0,
                        "overdueAmt": 0,
                        "preRepay": "N",
                        "overdue": "N"
                    },
                    {
                        "termNo": 8,
                        "shouldRepayDate": "20220527",
                        "termStatus": "PAYING",
                        "repayCategory": 1,
                        "termAmount": 47280,
                        "termPrincipal": 42811,
                        "termInterest": 4469,
                        "termPrinPenalty": 0,
                        "termInterPenalty": 0,
                        "termInsuranceAmount": 0,
                        "paidTermInsuranceAmount": 0,
                        "termFee": 0,
                        "paidTime": 0,
                        "paidTermAmount": 0,
                        "paidTermPrincipal": 0,
                        "paidTermInterest": 0,
                        "paidTermPrinPenalty": 0,
                        "paidTermInterPenalty": 0,
                        "paidTermFee": 0,
                        "overdueDays": 0,
                        "overdueAmt": 0,
                        "preRepay": "N",
                        "overdue": "N"
                    },
                    {
                        "termNo": 9,
                        "shouldRepayDate": "20220627",
                        "termStatus": "PAYING",
                        "repayCategory": 1,
                        "termAmount": 47280,
                        "termPrincipal": 43547,
                        "termInterest": 3733,
                        "termPrinPenalty": 0,
                        "termInterPenalty": 0,
                        "termInsuranceAmount": 0,
                        "paidTermInsuranceAmount": 0,
                        "termFee": 0,
                        "paidTime": 0,
                        "paidTermAmount": 0,
                        "paidTermPrincipal": 0,
                        "paidTermInterest": 0,
                        "paidTermPrinPenalty": 0,
                        "paidTermInterPenalty": 0,
                        "paidTermFee": 0,
                        "overdueDays": 0,
                        "overdueAmt": 0,
                        "preRepay": "N",
                        "overdue": "N"
                    },
                    {
                        "termNo": 10,
                        "shouldRepayDate": "20220727",
                        "termStatus": "PAYING",
                        "repayCategory": 1,
                        "termAmount": 47280,
                        "termPrincipal": 44538,
                        "termInterest": 2742,
                        "termPrinPenalty": 0,
                        "termInterPenalty": 0,
                        "termInsuranceAmount": 0,
                        "paidTermInsuranceAmount": 0,
                        "termFee": 0,
                        "paidTime": 0,
                        "paidTermAmount": 0,
                        "paidTermPrincipal": 0,
                        "paidTermInterest": 0,
                        "paidTermPrinPenalty": 0,
                        "paidTermInterPenalty": 0,
                        "paidTermFee": 0,
                        "overdueDays": 0,
                        "overdueAmt": 0,
                        "preRepay": "N",
                        "overdue": "N"
                    },
                    {
                        "termNo": 11,
                        "shouldRepayDate": "20220827",
                        "termStatus": "PAYING",
                        "repayCategory": 1,
                        "termAmount": 47280,
                        "termPrincipal": 45367,
                        "termInterest": 1913,
                        "termPrinPenalty": 0,
                        "termInterPenalty": 0,
                        "termInsuranceAmount": 0,
                        "paidTermInsuranceAmount": 0,
                        "termFee": 0,
                        "paidTime": 0,
                        "paidTermAmount": 0,
                        "paidTermPrincipal": 0,
                        "paidTermInterest": 0,
                        "paidTermPrinPenalty": 0,
                        "paidTermInterPenalty": 0,
                        "paidTermFee": 0,
                        "overdueDays": 0,
                        "overdueAmt": 0,
                        "preRepay": "N",
                        "overdue": "N"
                    },
                    {
                        "termNo": 12,
                        "shouldRepayDate": "20220927",
                        "termStatus": "PAYING",
                        "repayCategory": 1,
                        "termAmount": 48176,
                        "termPrincipal": 47201,
                        "termInterest": 975,
                        "termPrinPenalty": 0,
                        "termInterPenalty": 0,
                        "termInsuranceAmount": 0,
                        "paidTermInsuranceAmount": 0,
                        "termFee": 0,
                        "paidTime": 0,
                        "paidTermAmount": 0,
                        "paidTermPrincipal": 0,
                        "paidTermInterest": 0,
                        "paidTermPrinPenalty": 0,
                        "paidTermInterPenalty": 0,
                        "paidTermFee": 0,
                        "overdueDays": 0,
                        "overdueAmt": 0,
                        "preRepay": "N",
                        "overdue": "N"
                    }
                ],
                "extendRepayPlanItems": None
            }
        }
        self.update(api, mode)


if __name__ == "__main__":
    pass
