# -*- coding: utf-8 -*-
from biztest.util.easymock.easymock import Easymock
from biztest.util.tools.tools import *


class RepayYixinRongshengMock(Easymock):
    # /yixin/yixin_rongsheng/repay.repaymentPlan 还款计划查询
    # /yixin/yixin_rongsheng/calAllAmountInAdvanceSingle 还款试算
    # /yixin/yixin_rongsheng/repay.do 还款申请  已参数化，无需改动
    # /yixin/yixin_rongsheng/repay.result 还款结果查询

    def mock_yixin_rongsheng_repay_query_success(self, repay_amt="51913"):
        api = "/yixin/yixin_rongsheng/repay.result"
        mode = {
            "code": "0",
            "message": "成功",
            "data": {
                "repayStatus": "SUCCESS",
                "repayAmount": repay_amt,
                "repayResult": "已还款成功...",
                "failCode": None,
                "repayResultList": None
            }
        }
        self.update(api, mode)

    def mock_yixin_rongsheng_repay_trial(self, item_no, prin_amt="32442", int_amt="1000"):
        #  本金为当期本金
        api = "/yixin/yixin_rongsheng/calAllAmountInAdvanceSingle"
        mode = {
            "code": "0",
            "message": "成功",
            "data": {
                "outOrderNo": item_no,
                "lnsOveAmt": "0",
                "lnsOveInt": "0",
                "lnsOveFee": "0",
                "lnsDefInt": "0",
                "lnsLatAmt": "0",
                "lnsCurAmt": prin_amt,
                "lnsCurInt": int_amt,
                "lnsCurFee": "0",
                "remainPrin": "167558",
                "fuInterest": "0",
                "penaltyAmt": "0",
                "chargeFee": "0",
                "preRePayAmt": "201000",
                "lnsLatFAmt": "0",
                "avlFeeAmt": "0",
                "avlPrinAmt": "0",
                "contSystemFlag": "",
                "customDepositAmt": "0",
                "dataId": "",
                "dcompavlAmt": "0",
                "depositAmt": "0",
                "hireBuyPrice": "0",
                "insureDepositAmt": "0",
                "lnsOthFee": "0",
                "lnsPreFee": "0",
                "mortDepositAmt": "0",
                "prestoreAmt": "0",
                "repayDay": "",
                "totalFeeAmt": "0",
                "totalPrinAmt": "0",
                "currentPeriodChargeList": [],
                "frzAmtList": [],
                "totalChargeList": [],
                "totalOverDueChargeList": [
                    {
                        "chargeTypeCode": "FX",
                        "receivableCharge": "0"
                    },
                    {
                        "chargeTypeCode": "HKGLFWFZNJ",
                        "receivableCharge": "0"
                    },
                    {
                        "chargeTypeCode": "ZNJ",
                        "receivableCharge": "0"
                    },
                    {
                        "chargeTypeCode": "SYFWFZNJ",
                        "receivableCharge": "0"
                    },
                    {
                        "chargeTypeCode": "FWFZNJ",
                        "receivableCharge": "0"
                    }
                ],
                "totalPeriodChargeList": []
            }
        }
        self.update(api, mode)

    def mock_yixin_rongsheng_repay_plan_query(self):
        api = "/yixin/yixin_rongsheng/repay.repaymentPlan"
        mode = {
            "code": "0",
            "message": "成功",
            "data": {
                "contractAmt": "200000",
                "loanTerm": "6",
                "contBeginDate": "2022-10-08",
                "contEndDate": "2023-03-08",
                "repayDay": "2022-10-08",
                "repayTerm": "0",
                "extDelayBeginDate": "",
                "totalDelayCnt": "0",
                "extDelayTerm": "0",
                "extDelayDays": "0",
                "calDefIntEndDate": "",
                "prestoreAmt": "0",
                "feePrestoreAmt": "0",
                "unPaidPreFee": "0",
                "unPaidPenalty": "0",
                "totalUnPaidAmt": "200000",
                "totalUnPaidInt": "7653",
                "totalUnPaidFee": "0",
                "totalUnpaidFeeList": [],
                "totalUnPaidDefInt": "0",
                "totalUnPaidLatAmt": "0",
                "loanBalance": "200000",
                "recycleFlag": "0",
                "rpyPlanChgFlag": "00000001",
                "conDpsFlag": "0",
                "clearFlag": "",
                "repayPlanItems": [
                    {
                        "subSection": "1",
                        "repayTerm": "1",
                        "acctFlag": "0",
                        "delayFlag": "1",
                        "repayBeginDate": "2022-10-08",
                        "repayEndDate": "2022-10-08",
                        "repayDate": None,
                        "lnsCurAmt": "32442",
                        "lnsCurInt": "2167",
                        "lnsCurFee": "0",
                        "lnsDefInt": "0",
                        "lnsLatAmt": "0",
                        "lnsFeeAmt": "0",
                        "lnsOthAmt": "0",
                        "lnsRecPrin": "0",
                        "lnsRecInt": "0",
                        "lnsRecFee": "0",
                        "lnsRecDefInt": "0",
                        "lnsRecLatAmt": "0",
                        "lnsRecFeeAmt": "0",
                        "lnsRecOthAmt": "0",
                        "lnsDeartePrin": "0",
                        "lnsDearteInt": "0",
                        "lnsDearteFee": "0",
                        "lnsDearteDefInt": "0",
                        "lnsDearteLatAmt": "0",
                        "lnsDearteFeeAmt": "0",
                        "lnsDearteOthAmt": "0",
                        "unPaidAmt": "32442",
                        "unPaidInt": "2167",
                        "unPaidFee": "0",
                        "unPaidDefInt": "0",
                        "unPaidLatAmt": "0",
                        "unPaidFeeAmt": "0",
                        "unPaidLatOthAmt": "0",
                        "totalUnPaidAmt": "34609",
                        "prepayamt": "202167",
                        "overduePeriods": "0",
                        "overdueDays": "0",
                        "preIsRePay": None,
                        "lnsFeeInfoList": []
                    },
                    {
                        "subSection": "1",
                        "repayTerm": "2",
                        "acctFlag": "0",
                        "delayFlag": "1",
                        "repayBeginDate": "2022-11-08",
                        "repayEndDate": "2022-11-08",
                        "repayDate": None,
                        "lnsCurAmt": "32793",
                        "lnsCurInt": "1816",
                        "lnsCurFee": "0",
                        "lnsDefInt": "0",
                        "lnsLatAmt": "0",
                        "lnsFeeAmt": "0",
                        "lnsOthAmt": "0",
                        "lnsRecPrin": "0",
                        "lnsRecInt": "0",
                        "lnsRecFee": "0",
                        "lnsRecDefInt": "0",
                        "lnsRecLatAmt": "0",
                        "lnsRecFeeAmt": "0",
                        "lnsRecOthAmt": "0",
                        "lnsDeartePrin": "0",
                        "lnsDearteInt": "0",
                        "lnsDearteFee": "0",
                        "lnsDearteDefInt": "0",
                        "lnsDearteLatAmt": "0",
                        "lnsDearteFeeAmt": "0",
                        "lnsDearteOthAmt": "0",
                        "unPaidAmt": "32793",
                        "unPaidInt": "1816",
                        "unPaidFee": "0",
                        "unPaidDefInt": "0",
                        "unPaidLatAmt": "0",
                        "unPaidFeeAmt": "0",
                        "unPaidLatOthAmt": "0",
                        "totalUnPaidAmt": "34609",
                        "prepayamt": "169374",
                        "overduePeriods": "0",
                        "overdueDays": "0",
                        "preIsRePay": None,
                        "lnsFeeInfoList": []
                    },
                    {
                        "subSection": "1",
                        "repayTerm": "3",
                        "acctFlag": "0",
                        "delayFlag": "1",
                        "repayBeginDate": "2022-12-08",
                        "repayEndDate": "2022-12-08",
                        "repayDate": None,
                        "lnsCurAmt": "33149",
                        "lnsCurInt": "1460",
                        "lnsCurFee": "0",
                        "lnsDefInt": "0",
                        "lnsLatAmt": "0",
                        "lnsFeeAmt": "0",
                        "lnsOthAmt": "0",
                        "lnsRecPrin": "0",
                        "lnsRecInt": "0",
                        "lnsRecFee": "0",
                        "lnsRecDefInt": "0",
                        "lnsRecLatAmt": "0",
                        "lnsRecFeeAmt": "0",
                        "lnsRecOthAmt": "0",
                        "lnsDeartePrin": "0",
                        "lnsDearteInt": "0",
                        "lnsDearteFee": "0",
                        "lnsDearteDefInt": "0",
                        "lnsDearteLatAmt": "0",
                        "lnsDearteFeeAmt": "0",
                        "lnsDearteOthAmt": "0",
                        "unPaidAmt": "33149",
                        "unPaidInt": "1460",
                        "unPaidFee": "0",
                        "unPaidDefInt": "0",
                        "unPaidLatAmt": "0",
                        "unPaidFeeAmt": "0",
                        "unPaidLatOthAmt": "0",
                        "totalUnPaidAmt": "34609",
                        "prepayamt": "136225",
                        "overduePeriods": "0",
                        "overdueDays": "0",
                        "preIsRePay": None,
                        "lnsFeeInfoList": []
                    },
                    {
                        "subSection": "1",
                        "repayTerm": "4",
                        "acctFlag": "0",
                        "delayFlag": "1",
                        "repayBeginDate": "2023-01-08",
                        "repayEndDate": "2023-01-08",
                        "repayDate": None,
                        "lnsCurAmt": "33508",
                        "lnsCurInt": "1101",
                        "lnsCurFee": "0",
                        "lnsDefInt": "0",
                        "lnsLatAmt": "0",
                        "lnsFeeAmt": "0",
                        "lnsOthAmt": "0",
                        "lnsRecPrin": "0",
                        "lnsRecInt": "0",
                        "lnsRecFee": "0",
                        "lnsRecDefInt": "0",
                        "lnsRecLatAmt": "0",
                        "lnsRecFeeAmt": "0",
                        "lnsRecOthAmt": "0",
                        "lnsDeartePrin": "0",
                        "lnsDearteInt": "0",
                        "lnsDearteFee": "0",
                        "lnsDearteDefInt": "0",
                        "lnsDearteLatAmt": "0",
                        "lnsDearteFeeAmt": "0",
                        "lnsDearteOthAmt": "0",
                        "unPaidAmt": "33508",
                        "unPaidInt": "1101",
                        "unPaidFee": "0",
                        "unPaidDefInt": "0",
                        "unPaidLatAmt": "0",
                        "unPaidFeeAmt": "0",
                        "unPaidLatOthAmt": "0",
                        "totalUnPaidAmt": "34609",
                        "prepayamt": "102717",
                        "overduePeriods": "0",
                        "overdueDays": "0",
                        "preIsRePay": None,
                        "lnsFeeInfoList": []
                    },
                    {
                        "subSection": "1",
                        "repayTerm": "5",
                        "acctFlag": "0",
                        "delayFlag": "1",
                        "repayBeginDate": "2023-02-08",
                        "repayEndDate": "2023-02-08",
                        "repayDate": None,
                        "lnsCurAmt": "33871",
                        "lnsCurInt": "738",
                        "lnsCurFee": "0",
                        "lnsDefInt": "0",
                        "lnsLatAmt": "0",
                        "lnsFeeAmt": "0",
                        "lnsOthAmt": "0",
                        "lnsRecPrin": "0",
                        "lnsRecInt": "0",
                        "lnsRecFee": "0",
                        "lnsRecDefInt": "0",
                        "lnsRecLatAmt": "0",
                        "lnsRecFeeAmt": "0",
                        "lnsRecOthAmt": "0",
                        "lnsDeartePrin": "0",
                        "lnsDearteInt": "0",
                        "lnsDearteFee": "0",
                        "lnsDearteDefInt": "0",
                        "lnsDearteLatAmt": "0",
                        "lnsDearteFeeAmt": "0",
                        "lnsDearteOthAmt": "0",
                        "unPaidAmt": "33871",
                        "unPaidInt": "738",
                        "unPaidFee": "0",
                        "unPaidDefInt": "0",
                        "unPaidLatAmt": "0",
                        "unPaidFeeAmt": "0",
                        "unPaidLatOthAmt": "0",
                        "totalUnPaidAmt": "34609",
                        "prepayamt": "68846",
                        "overduePeriods": "0",
                        "overdueDays": "0",
                        "preIsRePay": None,
                        "lnsFeeInfoList": []
                    },
                    {
                        "subSection": "1",
                        "repayTerm": "6",
                        "acctFlag": "0",
                        "delayFlag": "1",
                        "repayBeginDate": "2023-03-08",
                        "repayEndDate": "2023-03-08",
                        "repayDate": None,
                        "lnsCurAmt": "34237",
                        "lnsCurInt": "371",
                        "lnsCurFee": "0",
                        "lnsDefInt": "0",
                        "lnsLatAmt": "0",
                        "lnsFeeAmt": "0",
                        "lnsOthAmt": "0",
                        "lnsRecPrin": "0",
                        "lnsRecInt": "0",
                        "lnsRecFee": "0",
                        "lnsRecDefInt": "0",
                        "lnsRecLatAmt": "0",
                        "lnsRecFeeAmt": "0",
                        "lnsRecOthAmt": "0",
                        "lnsDeartePrin": "0",
                        "lnsDearteInt": "0",
                        "lnsDearteFee": "0",
                        "lnsDearteDefInt": "0",
                        "lnsDearteLatAmt": "0",
                        "lnsDearteFeeAmt": "0",
                        "lnsDearteOthAmt": "0",
                        "unPaidAmt": "34237",
                        "unPaidInt": "371",
                        "unPaidFee": "0",
                        "unPaidDefInt": "0",
                        "unPaidLatAmt": "0",
                        "unPaidFeeAmt": "0",
                        "unPaidLatOthAmt": "0",
                        "totalUnPaidAmt": "34608",
                        "prepayamt": "34608",
                        "overduePeriods": "0",
                        "overdueDays": "0",
                        "preIsRePay": None,
                        "lnsFeeInfoList": []
                    }
                ],
                "preFeeInfoList": [],
                "totalUnpaidFeeAmt": "0"
            }
        }
        self.update(api, mode)


if __name__ == "__main__":
    pass
