#!/usr/bin/python
# -*- coding: UTF-8 -*-
capital_plan = {
    "india": [
        # {
        # "channel": "nbfc_f6_new",
        # "account": "sixsixsix",
        # "from_system": "ind",
        # "from_app": "ind005",
        # "source_type": "postservice30%_rate1‰_late7‰",
        # "rule": "(string.contains(#loan.refOrderType,'postservice30%_rate1‰') && #loan.totalAmount==(cmdb.apr(#loan,'36')+#loan.principalAmount*0.30)) ||(string.contains(#loan.refOrderType,'postservice35%_rate1‰') && #loan.totalAmount==(cmdb.apr(#loan,'36')+#loan.principalAmount*0.35)) ||(string.contains(#loan.refOrderType,'postservice43%_rate1‰') && #loan.totalAmount==(cmdb.apr(#loan,'36')+#loan.principalAmount*0.43)) ||(string.contains(#loan.refOrderType,'postservice40%_rate1‰') && #loan.totalAmount==(cmdb.apr(#loan,'36')+#loan.principalAmount*0.40)) ||(!string.contains(#loan.refOrderType,'post') && #loan.totalAmount==(cmdb.apr(#loan,'36')))"
        # },
        # {
        #     "channel": "nbfc_sunita",
        #     "account": "sunita",
        #     "rule": "(string.contains(#loan.refOrderType,'postservice30%_rate1‰') && #loan.totalAmount==(cmdb.apr(#loan,'36')+#loan.principalAmount*0.30)) ||(string.contains(#loan.refOrderType,'postservice35%_rate1‰') && #loan.totalAmount==(cmdb.apr(#loan,'36')+#loan.principalAmount*0.35)) ||(string.contains(#loan.refOrderType,'postservice43%_rate1‰') && #loan.totalAmount==(cmdb.apr(#loan,'36')+#loan.principalAmount*0.43)) ||(string.contains(#loan.refOrderType,'postservice40%_rate1‰') && #loan.totalAmount==(cmdb.apr(#loan,'36')+#loan.principalAmount*0.40)) ||(!string.contains(#loan.refOrderType,'post') && #loan.totalAmount==(cmdb.apr(#loan,'36')))",
        #     "from_system": "ind",
        #     "from_app": "ind005",
        #     "source_type": "postservice30%_rate1‰_late7‰",
        # },
        {
            "channel": "qp",
            "rule_code": "qp_0",
            "rule_desc": "qp_0期",
            "rule_family": "qp",
            "rule_content": "{\\\"name\\\":\\\"qp_0期总量\\\",\\\"rules\\\":[{\\\"name\\\":\\\"qp_0期总量\\\",\\\"rule\\\":\\\"asset.periodType==\\\'day\\\'\\\"}],\\\"output\\\":{\\\"key\\\":\\\"channel\\\",\\\"value\\\":\\\"qp\\\"}}",
            "rule_type": "supply",
            "rule_activation_group": "",
            "rule_limit_type": "strict",
            "rule_weight": 0,
            "rule_allow_overflow_rate": 0,
            "rule_product_code": "",
            "weight_value": 0,
            "weight_status": "active",
            "weight_first_route_status": "active",
            "weight_second_route_status": "inactive",
            "account": "qp",
            "rule": "(string.contains(#loan.refOrderType,'postservice30%_rate1‰') && #loan.totalAmount==(cmdb.apr(#loan,'36')+#loan.principalAmount*0.30)) ||(string.contains(#loan.refOrderType,'postservice54%_rate1‰') && #loan.totalAmount==(cmdb.apr(#loan,'36')+#loan.principalAmount*0.54))||(string.contains(#loan.refOrderType,'postservice35%_rate1‰') && #loan.totalAmount==(cmdb.apr(#loan,'36')+#loan.principalAmount*0.35)) ||(string.contains(#loan.refOrderType,'postservice43%_rate1‰') && #loan.totalAmount==(cmdb.apr(#loan,'36')+#loan.principalAmount*0.43)) ||(string.contains(#loan.refOrderType,'postservice40%_rate1‰') && #loan.totalAmount==(cmdb.apr(#loan,'36')+#loan.principalAmount*0.40)) ||(!string.contains(#loan.refOrderType,'post') && #loan.totalAmount==(cmdb.apr(#loan,'36')))",
            "from_system": "ind",
            "from_app": "ind005",
            "source_type": "postservice30%_rate1‰_late7%",
        }
    ],
    "thailand": [
        {
            "channel": "picocp_ams1",
            "rule_code": "picocp_ams1_0",
            "rule_desc": "picocp_ams1_0期",
            "rule_family": "picocp_ams1",
            "rule_content": "{\\\"name\\\":\\\"picocp_ams10期总量\\\",\\\"rules\\\":[{\\\"name\\\":\\\"picocp_ams1总量\\\",\\\"rule\\\":\\\"asset.periodType==\\\'day\\\'\\\"}],\\\"output\\\":{\\\"key\\\":\\\"channel\\\",\\\"value\\\":\\\"picocp_ams1\\\"}}",
            "rule_type": "supply",
            "rule_activation_group": "",
            "rule_limit_type": "strict",
            "rule_weight": 0,
            "rule_allow_overflow_rate": 0,
            "rule_product_code": "",
            "weight_value": 0,
            "weight_status": "active",
            "weight_first_route_status": "active",
            "weight_second_route_status": "active",
            "account": "amberstar1",
            "rule": "#loan.totalAmount==cmdb.aprByDay(#loan, str(#loan.rateVarInfo.fees.interest),'365per_year','D+0','D+0')",
            "from_system": "tha",
            "from_app": "mango",
            "source_type": "game_bill",
            "fees": {"interest": "35.77"},
            "late_num": "late0.098%"
        },
        {
            "channel": "picoqr_ams1",
            "rule_code": "picoqr_ams1_bangkok_0",
            "rule_desc": "picoqr_ams1_bangkok_0期",
            "rule_family": "picoqr_ams1",
            "rule_content": "{\\\"name\\\":\\\"PicoQR总量-曼谷\\\",\\\"rules\\\":[{\\\"name\\\":\\\"PicoQR总量-曼谷\\\",\\\"rule\\\":\\\"asset.periodType==\\\'day\\\' and borrower.areaCode==\\\'10\\\'\\\"}],\\\"output\\\":{\\\"key\\\":\\\"channel\\\",\\\"value\\\":\\\"picoqr_ams1\\\"}}",
            "rule_type": "supply",
            "rule_activation_group": "",
            "rule_limit_type": "strict",
            "rule_weight": 0,
            "rule_allow_overflow_rate": 0,
            "rule_product_code": "bangkok",
            "weight_value": 0,
            "weight_status": "active",
            "weight_first_route_status": "active",
            "weight_second_route_status": "active",
            "account": "amberstar2",
            "rule": "#loan.totalAmount==cmdb.aprByDay(#loan, str(#loan.rateVarInfo.fees.interest),'365per_year','D+0','D+0')",
            "from_system": "tha",
            "from_app": "mango",
            "source_type": "game_bill",
            "fees": {"interest": "35.77"},
            "late_num": "late0.098%"
        },
        {
            "channel": "picoqr_ams1",
            "rule_code": "picoqr_ams1_saraburi_0",
            "rule_desc": "picoqr_ams1_saraburi_0期",
            "rule_family": "picoqr_ams1",
            "rule_content": "{\\\"name\\\":\\\"PicoQR总量-北标府\\\",\\\"rules\\\":[{\\\"name\\\":\\\"PicoQR总量-北标府\\\",\\\"rule\\\":\\\"asset.periodType==\\\'day\\\' and borrower.areaCode==\\\'19\\\'\\\"}],\\\"output\\\":{\\\"key\\\":\\\"channel\\\",\\\"value\\\":\\\"picoqr_ams1\\\"}}",
            "rule_type": "supply",
            "rule_activation_group": "",
            "rule_limit_type": "strict",
            "rule_weight": 0,
            "rule_allow_overflow_rate": 0,
            "rule_product_code": "saraburi",
            "weight_value": 0,
            "weight_status": "active",
            "weight_first_route_status": "active",
            "weight_second_route_status": "active",
            "account": "amberstar2",
            "rule": "#loan.totalAmount==cmdb.aprByDay(#loan, str(#loan.rateVarInfo.fees.interest),'365per_year','D+0','D+0')",
            "from_system": "tha",
            "from_app": "mango",
            "source_type": "game_bill",
            "fees": {"interest": "35.77"},
            "late_num": "late0.098%"
        },
        {
            "channel": "picoqr_ams1",
            "rule_code": "picoqr_ams1_korat_0",
            "rule_desc": "picoqr_ams1_korat_0期",
            "rule_family": "picoqr_ams1",
            "rule_content": "{\\\"name\\\":\\\"PicoQR总量-呵叻府\\\",\\\"rules\\\":[{\\\"name\\\":\\\"PicoQR总量-呵叻府\\\",\\\"rule\\\":\\\"asset.periodType==\\\'day\\\' and borrower.areaCode==\\\'30\\\'\\\"}],\\\"output\\\":{\\\"key\\\":\\\"channel\\\",\\\"value\\\":\\\"picoqr_ams1\\\"}}",
            "rule_type": "supply",
            "rule_activation_group": "",
            "rule_limit_type": "strict",
            "rule_weight": 0,
            "rule_allow_overflow_rate": 0,
            "rule_product_code": "korat",
            "weight_value": 0,
            "weight_status": "active",
            "weight_first_route_status": "active",
            "weight_second_route_status": "active",
            "account": "amberstar2",
            "rule": "#loan.totalAmount==cmdb.aprByDay(#loan, str(#loan.rateVarInfo.fees.interest),'365per_year','D+0','D+0')",
            "from_system": "tha",
            "from_app": "mango",
            "source_type": "game_bill",
            "fees": {"interest": "35.77"},
            "late_num": "late0.098%"
        },
        {
            "channel": "picocp_ams2",
            "rule_code": "picocp_ams2_0",
            "rule_desc": "picocp_ams2_0期",
            "rule_family": "picocp_ams2",
            "rule_content": "{\\\"name\\\":\\\"picocp_ams2 0期总量\\\",\\\"rules\\\":[{\\\"name\\\":\\\"picocp_ams2总量\\\",\\\"rule\\\":\\\"asset.periodType==\\\'day\\\'\\\"}],\\\"output\\\":{\\\"key\\\":\\\"channel\\\",\\\"value\\\":\\\"picocp_ams2\\\"}}",
            "rule_type": "supply",
            "rule_activation_group": "",
            "rule_limit_type": "strict",
            "rule_weight": 0,
            "rule_allow_overflow_rate": 0,
            "rule_product_code": "",
            "weight_value": 0,
            "weight_status": "active",
            "weight_first_route_status": "active",
            "weight_second_route_status": "active",
            "account": "amberstar1",
            "rule": "#loan.totalAmount==cmdb.aprByDay(#loan, str(#loan.rateVarInfo.fees.interest),'365per_year','D+0','D+0')",
            "from_system": "tha",
            "from_app": "mango",
            "source_type": "game_bill",
            "fees": {"interest": "35.77"},
            "late_num": "late0.098%"
        },
        {
            "channel": "picoqr_ams2",
            "rule_code": "picoqr_ams2_0",
            "rule_desc": "picoqr_ams2_0期",
            "rule_family": "picoqr_ams2",
            "rule_content": "{\\\"name\\\":\\\"picoqr_ams2 0期总量\\\",\\\"rules\\\":[{\\\"name\\\":\\\"picoqr_ams2总量\\\",\\\"rule\\\":\\\"asset.periodType==\\\'day\\\'\\\"}],\\\"output\\\":{\\\"key\\\":\\\"channel\\\",\\\"value\\\":\\\"picoqr_ams2\\\"}}",
            "rule_type": "supply",
            "rule_activation_group": "",
            "rule_limit_type": "strict",
            "rule_weight": 0,
            "rule_allow_overflow_rate": 0,
            "rule_product_code": "",
            "weight_value": 0,
            "weight_status": "active",
            "weight_first_route_status": "active",
            "weight_second_route_status": "active",
            "account": "amberstar1",
            "rule": "#loan.totalAmount==cmdb.aprByDay(#loan, str(#loan.rateVarInfo.fees.interest),'365per_year','D+0','D+0')",
            "from_system": "tha",
            "from_app": "mango",
            "source_type": "game_bill",
            "fees": {"interest": "35.77"},
            "late_num": "late0.098%"
        },
        {
            "channel": "pico_bangkok",
            "rule_code": "pico_bangkok_0",
            "rule_desc": "pico_bangkok_0期",
            "rule_family": "pico_bangkok",
            "rule_content": "{\\\"name\\\":\\\"pico_bangkok0期总量\\\",\\\"rules\\\":[{\\\"name\\\":\\\"pico_bangkok总量\\\",\\\"rule\\\":\\\"asset.periodType==\\\'day\\\'\\\"}],\\\"output\\\":{\\\"key\\\":\\\"channel\\\",\\\"value\\\":\\\"pico_bangkok\\\"}}",
            "rule_type": "supply",
            "rule_activation_group": "",
            "rule_limit_type": "strict",
            "rule_weight": 0,
            "rule_allow_overflow_rate": 0,
            "rule_product_code": "",
            "weight_value": 0,
            "weight_status": "active",
            "weight_first_route_status": "active",
            "weight_second_route_status": "active",
            "account": "amberstar1",
            "rule": "(#loan.refOrderType=='service20_rate1%_late1%' && #loan.totalAmount==(cmdb.apr(#loan,'36')+#loan.principalAmount*0.20)) || (#loan.refOrderType=='test_bill' && #loan.totalAmount==(cmdb.apr(#loan,'36'))) || (#loan.totalAmount==cmdb.aprByDay(#loan, str(#loan.rateVarInfo.fees.interest),'365per_year','D+0','D+0'))",
            "from_system": "tha",
            "from_app": "mango",
            "source_type": "game_bill",
            "fees": {"interest": "35.77"},
            "late_num": "late0.098%"
        }
    ],
    "philippines": [
        {
            "channel": "copper_stone",
            "rule_code": "copper_stone_0",
            "rule_desc": "copper_stone_0期",
            "rule_family": "copper_stone",
            "rule_content": "{\\\"name\\\":\\\"copper_stone_0期总量\\\",\\\"rules\\\":[{\\\"name\\\":\\\"copper_stone_0期总量\\\",\\\"rule\\\":\\\"asset.periodType==\\\'day\\\'\\\"}],\\\"output\\\":{\\\"key\\\":\\\"channel\\\",\\\"value\\\":\\\"copper_stone\\\"}}",
            "rule_type": "supply",
            "rule_activation_group": "",
            "rule_limit_type": "strict",
            "rule_weight": 0,
            "rule_allow_overflow_rate": 0,
            "rule_product_code": "",
            "weight_value": 0,
            "weight_status": "active",
            "weight_first_route_status": "active",
            "weight_second_route_status": "inactive",
            "account": "copperstone",
            "rule": "(#loan.refOrderType=='pl01' && #loan.totalAmount==cmdb.aprByDay(#loan, str(#loan.rateVarInfo.fees.interest),'360','D+0','D+0')+#loan.principalAmount*#loan.rateVarInfo.fees.fin_service/100)",
            "from_system": "phl",
            "from_app": "jasmine",
            "source_type": "pl01",
            "withdraw_type": "online",
            "fees": {"interest": "36.00", "fin_service": "50.00"},
            "late_num": "late7%"
        },
        {
            "channel": "glitter",
            "rule_code": "glitter_0",
            "rule_desc": "glitter_0期",
            "rule_family": "glitter",
            "rule_content": "{\\\"name\\\":\\\"glitter_0期总量\\\",\\\"rules\\\":[{\\\"name\\\":\\\"glitter_0期总量\\\",\\\"rule\\\":\\\"asset.periodType==\\\'day\\\'\\\"}],\\\"output\\\":{\\\"key\\\":\\\"channel\\\",\\\"value\\\":\\\"glitter\\\"}}",
            "rule_type": "supply",
            "rule_activation_group": "",
            "rule_limit_type": "strict",
            "rule_weight": 0,
            "rule_allow_overflow_rate": 0,
            "rule_product_code": "",
            "weight_value": 0,
            "weight_status": "active",
            "weight_first_route_status": "active",
            "weight_second_route_status": "inactive",
            "account": "glitter",
            "rule": "(#loan.refOrderType=='pl01' && #loan.totalAmount==cmdb.aprByDay(#loan, str(#loan.rateVarInfo.fees.interest),'360','D+0','D+0')+#loan.principalAmount*#loan.rateVarInfo.fees.fin_service/100)",
            "from_system": "phl",
            "from_app": "jasmine",
            "source_type": "pl01",
            "withdraw_type": "online",
            "fees": {"interest": "36.00", "fin_service": "50.00"},
            "late_num": "late7%"
        }
    ],
    "mexico": [
        {
            "channel": "mangguo",
            "rule_code": "mangguo_0",
            "rule_desc": "mangguo_0期",
            "rule_family": "mangguo",
            "rule_content": "{\\\"name\\\":\\\"mangguo_0期总量\\\",\\\"rules\\\":[{\\\"name\\\":\\\"mangguo_0期总量\\\",\\\"rule\\\":\\\"asset.periodType==\\\'day\\\'\\\"}],\\\"output\\\":{\\\"key\\\":\\\"channel\\\",\\\"value\\\":\\\"mangguo\\\"}}",
            "rule_type": "supply",
            "rule_activation_group": "",
            "rule_limit_type": "strict",
            "rule_weight": 0,
            "rule_allow_overflow_rate": 0,
            "rule_product_code": "",
            "weight_value": 0,
            "weight_status": "active",
            "weight_first_route_status": "active",
            "weight_second_route_status": "inactive",
            "account": "alibey",
            "rule": "#loan.totalAmount==cmdb.aprByDay(#loan, str(#loan.rateVarInfo.fees.interest),'360','D+0','D+0')+#loan.principalAmount*#loan.rateVarInfo.fees.fin_service/100",
            "from_system": "mex",
            "from_app": "ginkgo",
            "source_type": "pl01",
            "fees": {"interest": "36.00", "fin_service": "30.00"},
            "late_num": "late5%"
        },
        {
            "channel": "kadapul",
            "rule_code": "kadapul_0",
            "rule_desc": "kadapul_0期",
            "rule_family": "kadapul",
            "rule_content": "{\\\"name\\\":\\\"kadapul_0期总量\\\",\\\"rules\\\":[{\\\"name\\\":\\\"kadapul_0期总量\\\",\\\"rule\\\":\\\"asset.periodType==\\\'day\\\'\\\"}],\\\"output\\\":{\\\"key\\\":\\\"channel\\\",\\\"value\\\":\\\"kadapul\\\"}}",
            "rule_type": "supply",
            "rule_activation_group": "",
            "rule_limit_type": "strict",
            "rule_weight": 0,
            "rule_allow_overflow_rate": 0,
            "rule_product_code": "",
            "weight_value": 0,
            "weight_status": "active",
            "weight_first_route_status": "active",
            "weight_second_route_status": "inactive",
            "account": "alibey",
            "rule": "#loan.totalAmount==cmdb.aprByDay(#loan, str(#loan.rateVarInfo.fees.interest),'360','D+0','D+0')+#loan.principalAmount*#loan.rateVarInfo.fees.fin_service/100",
            "from_system": "mex",
            "from_app": "ginkgo",
            "source_type": "pl01",
            "fees": {"interest": "36.00", "fin_service": "30.00"},
            "late_num": "late5%"
        }
    ],
    "pakistan": [
        # {
        #     "channel": "qiss",
        #     "rule_code": "qiss_0",
        #     "rule_desc": "qiss_0期",
        #     "rule_family": "qiss",
        #     "rule_content": "{\\\"name\\\":\\\"qiss_0期总量\\\",\\\"rules\\\":[{\\\"name\\\":\\\"qiss_0期总量\\\",\\\"rule\\\":\\\"asset.periodType==\\\'day\\\'\\\"}],\\\"output\\\":{\\\"key\\\":\\\"channel\\\",\\\"value\\\":\\\"qiss\\\"}}",
        #     "rule_type": "supply",
        #     "rule_activation_group": "",
        #     "rule_limit_type": "strict",
        #     "rule_weight": 0,
        #     "rule_allow_overflow_rate": 0,
        #     "rule_product_code": "",
        #     "weight_value": 0,
        #     "weight_status": "active",
        #     "weight_first_route_status": "active",
        #     "weight_second_route_status": "inactive",
        #     "account": "qiss",
        #     "rule": "(#loan.refOrderType=='pl01' && #loan.totalAmount==cmdb.aprByDay(#loan, '0','360','D+0','D+0')+#loan.principalAmount*#loan.rateVarInfo.fees.fin_service/100)",
        #     "from_system": "pak",
        #     "from_app": "pak001",
        #     "source_type": "pl01",
        #     "fees": {"fin_service": "33.00"},
        #     "late_num": "late2%"
        # },
        {
            "channel": "goldlion",
            "rule_code": "goldlion_0",
            "rule_desc": "goldlion_0期",
            "rule_family": "goldlion",
            "rule_content": "{\\\"name\\\":\\\"goldlion_0期总量\\\",\\\"rules\\\":[{\\\"name\\\":\\\"goldlion_0期总量\\\",\\\"rule\\\":\\\"asset.periodType==\\\'day\\\'\\\"}],\\\"output\\\":{\\\"key\\\":\\\"channel\\\",\\\"value\\\":\\\"goldlion\\\"}}",
            "rule_type": "supply",
            "rule_activation_group": "",
            "rule_limit_type": "strict",
            "rule_weight": 0,
            "rule_allow_overflow_rate": 0,
            "rule_product_code": "",
            "weight_value": 0,
            "weight_status": "active",
            "weight_first_route_status": "active",
            "weight_second_route_status": "inactive",
            "account": "goldlion",
            "rule": "(#loan.refOrderType=='pl01' && #loan.totalAmount==cmdb.aprByDay(#loan, '0','360','D+0','D+0')+#loan.principalAmount*#loan.rateVarInfo.fees.fin_service/100)",
            "from_system": "pak",
            "from_app": "pak001",
            "source_type": "pl01",
            "fees": {"fin_service": "33.00"},
            "late_num": "late2%"
        }
    ]
}
